x-airflow-common: &airflow-common
  image: apache/airflow:2.10.5
  env_file:
    - .env
  volumes:
    - airflow_logs:/opt/airflow/logs
    - airflow_config:/opt/airflow/config
    - airflow_plugins:/opt/airflow/plugins
    - ../pipelines:/opt/pipelines
  user: "${AIRFLOW_UID:-50000}:0"

services:
  airflow-worker:
    <<: *airflow-common
    hostname: ${CELERY_HOSTNAME}
    command: airflow celery worker --autoscale 4,1 -H ${CELERY_HOSTNAME} -q ${QUEUES}
    environment:
      DUMB_INIT_SETSID: "0"
      PYTHONPATH: ${PYTHONPATH}
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD-SHELL"
        - "airflow jobs check --job-type WorkerJob --hostname \"$${HOSTNAME}\""
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  airflow_logs:
  airflow_config:
  airflow_plugins: